server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

security:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/security_key_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    minimum-idle: 5
    maximum-pool-size: 20
    idle-timeout: 300000
    connection-timeout: 20000
    pool-name: SecurityHikariCP
  crypto:
    phone-key: 1234567890123456
    email-key: abcdefghijklmnop
    id-card-key: ABCDEFGHIJKLMNOP
    algorithm: SM4
    key-expire-minutes: 30

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.livelab.user.entity
